apiVersion: batch/v1
kind: Job
metadata:
  name: truck-2
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: truck-data-generator-job
        image: d2iqdemo/truck-data-generator
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: API
          value: "truck-data-api-svc:8080"
        - name: MODE
          value: "Random"
        - name: ROUTE # 1,2 or 3
          value: "2"
        - name: DAYTIME # Day/Night
          value: "Day"
        - name: HEATING # On=True Off=False
          value: "True"
        - name: WEATHER # Clear/Rainy/Foggy/Snowy
          value: "Rainy"
        - name: SEASON # Spring/Summer/Autumn/Winter
          value: "Summer"
        - name: SPEED # Average Speed between 60 and 100
          value: "1"
        - name: STEREO # On=True Off=False
          value: "True"
        - name: PHONE # Loading Yes=True No=False
          value: "True"
        - name: TLOAD # 0 to 100 in %
          value: "50"
        - name: COUNTRY
          value: "UK"
      restartPolicy: Never