
apiVersion: v1
kind: Service
metadata:
  name: truck-demo-ui-svc
spec:
  type: LoadBalancer
  selector:
    app: truck-demo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: truck-demo-ui
  name: truck-demo-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: truck-demo-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: truck-demo-ui
    spec:
      containers:
      - image: d2iqdemo/truck-demo-ui:latest
        imagePullPolicy: Always
        name: truck-demo-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CURRENT_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENV_API_URL
          valueFrom:
            configMapKeyRef:
              name: dataservices
              key: API
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 1
status: {}
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  annotations:
#    kubernetes.io/ingress.class: traefik
#    traefik.ingress.kubernetes.io/rewrite-target: /
#  name: truck-demo-ui
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /demo-ui
#        pathType: Prefix
#        backend:
#          service:
#            name: truck-demo-ui-svc
#            port: 
#              number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: truck-data-connector-ingressroute
spec:
  routes:
    - match: PathPrefix(`/data-connector`)
      kind: Rule
      services:
        - name: truck-data-connector-svc
          port: data-connector
      middlewares:
        - name: data-connector-stripprefix
  tls:
    secretName: tls-data-connector
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: data-connector-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /data-connector
    forceSlash: true
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-data-connector
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
